blank_issues_enabled: false
contact_links:
  - name: GABI discussion Q&A
    url: https://github.com/bio-raum/gabi/discussions/
    about: Please ask and answer questions here. Don't forget to tag the maintainers!
