---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: taxonkit_lineage
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::taxonkit=0.18.0
